---
- name: Install and Set up RabbitMQ with user
  hosts: rmqsrvgrp
  # from ansible.cfg
  gather_facts: no

  tasks:
    - name: Install Erlang Repository Package
      apt:
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      tags:
        - package


    - name: Add an Erlang soluton public key
      apt_key:
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
      # add the public key below
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package


    - name: Install Erlang
      apt:
      # install erlang from the repository above
        name: erlang
        update_cache: yes
        cache_valid_time: 86400
        state: present
      tags:
        - package

  
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present
      tags:
        - package






    # - name: Add repository for rabbitmq
    #   apt_repository:
    #   # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
    #     repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
    #     state: present
    #   tags:
    #     - package


    - name: Add RabbitMQ APT Repository
      apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main
      state: present







    - name: Install Rabbit MQ
      apt:
        name: rabbitmq-server
        # will fetch the packages list in above repo
        state: present
        update_cache: yes
        tags:
          - package


    - name: Start and enable RMQ service
      service: 
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    
    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
        # put the content above into the dest config file above
      notify:
        - Restart RMQ
      tags:
        - conf


    - name: Configure the rabbitmq username and password
      rabbitmq_user:
      # https://docs.ansible.com/ansible/latest/collections/community/rabbitmq/rabbitmq_user_module.html
        user: test
        password: test
        # see the provision-stack/templates/application.j2 file. rabbitmq.username=test and rabbitmq.password=test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
      # notify the handler below to restart
        - Restart RMQ
      tags:
        - conf


    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
      # https://docs.ansible.com/ansible/latest/collections/community/rabbitmq/rabbitmq_plugin_module.html
        names: rabbitmq_management
        state: enabled
      notify:
      # notify the handler below to restart
        - Restart RMQ
      tags:
        - package


  handlers:
  # this is executed as the last task.
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
